on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      version:
        required: false
        type: string
env:
  GHCR_ORG: ${{ vars.GHCR_ORG }}
jobs:
  update_job:
    name: update service
    runs-on: ubuntu-latest
    if: ${{ !contains(github.repository, 'util-orch-template') }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHCR_TOKEN }}
      - name: announce
        run: |
          echo "Updating [${{ inputs.repository }}] to [${{ inputs.version }}]"
      - name: update service
        uses: mikefarah/yq@master
        if: ${{ inputs.version }}
        with:
          cmd: yq e -i '.${{ inputs.repository }}|="${{ inputs.version }}"' ./releases.yaml
      - name: remove service
        uses: mikefarah/yq@master
        if: ${{ !inputs.version }}
        with:
          cmd: yq e -i '.${{ inputs.repository }}|=sub("-deleted", "") + "-deleted"' ./releases.yaml
      - name: commit updates
        run: |
          sort -o ./releases.yaml ./releases.yaml
          cat ./releases.yaml
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "${{ vars.GHCR_USER }}@ndvr.com"
            git config --global user.name "${{ vars.GHCR_USER }}"
            git commit -am "chore: â¬† [${{ inputs.repository }}] to [${{ inputs.version }}]"
            git push origin HEAD:main
          fi

